StylesPath = .github/styles
MinAlertLevel = error
Packages = write-good

[*.md]
BasedOnStyles = write-good

# Disable opinionated style rules
write-good.Passive = NO
write-good.Weasel = NO
write-good.TooWordy = NO
write-good.E-Prime = NO
write-good.So = NO
write-good.ThereIs = NO

# Ignore code fences and inline code
BlockIgnores = (?s)```.*?```
TokenIgnores = (`.+?`)